/* Windows Terminal scheme + PowerShell/PSReadLine profile.
 *
 * Ours: windows/terminal/indigo-glass.scheme.json (GENERATED by
 * tokens/codegen.py's emit_wt_scheme() — see CLAUDE.md "Never hand-edit";
 * read raw here, never edited) and
 * windows/powershell/Microsoft.PowerShell_profile.ps1 (hand-kept, the
 * `-Colors` hashtable parsed by psreadline.ts).
 *
 * Stock: Windows Terminal's built-in "Campbell" scheme
 * (fixtures/stock/windows-terminal/Campbell.jsonc, reconstructed from
 * microsoft/terminal source — see that file's header) and PSReadLine's own
 * compiled-in default colours (PSReadLine/Cmdlets.cs DefaultXColor consts,
 * resolved through Campbell via consoleColors.ts — a ConsoleColor is not a
 * hex value, it is a legacy console colour name that gets painted using
 * whatever scheme the terminal is running, exactly as a starship named
 * colour is painted using the Konsole surface's palette).
 *
 * This host has no Windows install to verify against; see index.ts meta.live.
 */
import schemeText from '../../../../../windows/terminal/indigo-glass.scheme.json?raw';
import profileText from '../../../../../windows/powershell/Microsoft.PowerShell_profile.ps1?raw';
import campbellText from '../../../../fixtures/stock/windows-terminal/Campbell.jsonc?raw';
import { parseJsoncDoc } from '../shell/jsonc';
import { parsePwshColors, type PwshColorEntry } from './psreadline';
import { PSREADLINE_STOCK_CONSOLE_COLOR, resolveConsoleColor, type WtSlot } from './consoleColors';
import { cssVars } from '../surface';
import type { IniDoc } from '../ini';
import type { KeyVars } from '../coverage';

export const WT_SLOTS: WtSlot[] = [
  'black', 'red', 'green', 'yellow', 'blue', 'purple', 'cyan', 'white',
  'brightBlack', 'brightRed', 'brightGreen', 'brightYellow', 'brightBlue', 'brightPurple', 'brightCyan', 'brightWhite'
];

export type WtModel = {
  scheme: IniDoc;
  name: string;
  background: string;
  foreground: string;
  cursorColor: string;
  selectionBackground: string;
  ansi: Record<WtSlot, string>;
  ps: PwshColorEntry[];
  psDoc: IniDoc | null;
};

function schemeModel(doc: IniDoc): Pick<WtModel, 'scheme' | 'name' | 'background' | 'foreground' | 'cursorColor' | 'selectionBackground' | 'ansi'> {
  const g = (k: string) => doc.get('', k) ?? '';
  const ansi = Object.fromEntries(WT_SLOTS.map((s) => [s, g(s)])) as Record<WtSlot, string>;
  return { scheme: doc, name: g('name'), background: g('background'), foreground: g('foreground'), cursorColor: g('cursorColor'), selectionBackground: g('selectionBackground'), ansi };
}

function buildOurs(): WtModel {
  const doc = parseJsoncDoc(schemeText);
  const { entries, doc: psDoc } = parsePwshColors(profileText);
  return { ...schemeModel(doc), ps: entries, psDoc };
}

function buildStock(): WtModel {
  const doc = parseJsoncDoc(campbellText);
  const base = schemeModel(doc);
  const scheme: Record<string, string> = { ...base.ansi };
  const ps: PwshColorEntry[] = Object.entries(PSREADLINE_STOCK_CONSOLE_COLOR).map(([name, consoleColor]) => {
    const hex = resolveConsoleColor(consoleColor, scheme) ?? '#FFFFFF';
    return { name, kind: 'hex', raw: consoleColor, hex } as PwshColorEntry;
  });
  return { ...base, ps, psDoc: null };
}

export const ours = buildOurs();
export const stock = buildStock();

/* Coverage: every field of the shipped scheme.json, and every key inside the
 * shipped `-Colors` hashtable (the only colour-bearing part of profile.ps1 —
 * EditMode/PredictionSource/key handlers/zoxide/fnm below it carry no
 * colour, so they are outside this surface's coverage the same way Konsole's
 * General/Opacity or KDE's shadeSortColumn sit outside theirs: shown
 * literally in the settings table via doc.get(), never colour-bound). */
export const KEY_VARS: KeyVars = {};
const bind = (key: string, ...vars: string[]) => { (KEY_VARS[key] ??= []).push(...vars); };
bind('/background', 'wt-bg');
bind('/foreground', 'wt-fg');
bind('/cursorColor', 'wt-cursor');
bind('/selectionBackground', 'wt-selection');
for (const s of WT_SLOTS) bind(`/${s}`, `wt-ansi-${s}`);
/* PSReadLine -Colors entries -> ps-<lowercased name> (ansi-pair entries get
   both -fg and -bg). Bound here (not touched via doc.get in the page) so the
   coverage check is driven by the same CSS-var mechanism every other
   colour-bearing key in this surface uses. */
for (const e of ours.ps) {
  const slug = e.name.toLowerCase();
  if (e.kind === 'hex') bind(`/${e.name}`, `ps-${slug}`);
  else bind(`/${e.name}`, `ps-${slug}-fg`, `ps-${slug}-bg`);
}

export function laneVars(m: WtModel): string {
  const v: Record<string, string> = {
    'wt-bg': m.background, 'wt-fg': m.foreground, 'wt-cursor': m.cursorColor, 'wt-selection': m.selectionBackground,
    'desk-bg': m.background, 'desk-font': '"Cascadia Mono", "Iosevka Custom Condensed", monospace'
  };
  for (const s of WT_SLOTS) v[`wt-ansi-${s}`] = m.ansi[s];
  for (const e of m.ps) {
    const slug = e.name.toLowerCase();
    if (e.kind === 'hex') v[`ps-${slug}`] = e.hex;
    else { v[`ps-${slug}-fg`] = e.fg; v[`ps-${slug}-bg`] = e.bg; }
  }
  return cssVars(v);
}
