<script lang="ts">
  /* Shopee (light-only site): #main with the orange .shopee-top header and
   * searchbar, carousel with stardust dots and arrows, category list, mall
   * section, flash sale with countdown, product grid, stardust controls,
   * dropdown, modal, toast, alerts, voucher, footer. */
  import './stock.css';
  import SitePage from '../SitePage.svelte';
  import Section from '$lib/nb/Section.svelte';
  import Pair from '../Pair.svelte';
  import type { Site } from '../registry';
  let { site }: { site: Site } = $props();
</script>

<SitePage {site}>
  <Section id="home" title="Homepage" lead="#main › .shopee-top (.navbar__link*, .shopee-searchbar-input, .btn-solid-primary) › carousel (.stardust-carousel__dot*, .stardust-carousel__arrow, .carousel-arrow) › .home-category-list › .homepage-mall-section › flash sale (.shopee-countdown-timer__colon) › footer" min="760px">
    <Pair name=".shopee-top .navbar__link .shopee-searchbar-input__input .btn-solid-primary" span="full">
      <div id="main"><div class="shopee-top shopee-top--sticky"><div class="navbar"><a class="navbar__link" href="#"><span class="navbar__link-text">Seller Centre</span></a><span class="sep"></span><a class="navbar__link" href="#"><span class="navbar__link-text">Start Selling</span></a><span class="sep"></span><a class="navbar__link" href="#"><span class="navbar__link-text">Download</span></a><span class="sep"></span><a class="navbar__link" href="#"><span class="navbar__link-text">Follow us on</span> ⓕ ⓘ</a><div class="right"><a class="navbar__link" href="#">🔔 <span class="navbar__link-text">Notifications</span></a><a class="navbar__link" href="#">? <span class="navbar__link-text">Help</span></a><a class="navbar__link" href="#">🌐 <span class="navbar__link-text">English</span> ▾</a><a class="navbar__link navbar__link--signup" href="#"><span class="navbar__link-text">Sign Up</span></a><span class="sep"></span><a class="navbar__link" href="#"><span class="navbar__link-text">Log In</span></a></div></div>
        <div class="header-main"><span class="logo">Shopee</span><div class="shopee-searchbar"><div class="shopee-searchbar-input"><input class="shopee-searchbar-input__input" placeholder="Sign up and get 100% off on your first order" /><button class="btn-solid-primary"><i>🔍</i></button></div><div class="hints"><a href="#">Laptop</a><a href="#">Mechanical Keyboard</a><a href="#">USB-C Dock</a><a href="#">Monitor</a><a href="#">Mouse</a></div></div><span class="cart">🛒<span class="cart-number-badge">3</span></span></div></div>
        <div class="container">
          <div data-art class="stardust-carousel">9.25 PAYDAY SALE<div class="stardust-carousel__dots"><span class="stardust-carousel__dot stardust-carousel__dot--active"></span><span class="stardust-carousel__dot"></span><span class="stardust-carousel__dot"></span><span class="stardust-carousel__dot"></span></div><button class="stardust-carousel__arrow stardust-carousel__arrow--prev"><i>‹</i></button><button class="carousel-arrow next"><i>›</i></button></div>
          <div class="home-category-list"><div class="shopee-header-section__header"><span class="shopee-header-section__header__title">Categories</span></div><div class="home-category-list__grid"><a class="home-category-list__category-grid" href="#"><span class="img"></span><span>Computers &amp; Accessories</span></a><a class="home-category-list__category-grid" href="#"><span class="img"></span><span>Mobiles &amp; Gadgets</span></a><a class="home-category-list__category-grid" href="#"><span class="img"></span><span>Home Appliances</span></a><a class="home-category-list__category-grid" href="#"><span class="img"></span><span>Men's Apparel</span></a><a class="home-category-list__category-grid" href="#"><span class="img"></span><span>Groceries</span></a><a class="home-category-list__category-grid" href="#"><span class="img"></span><span>Gaming</span></a></div></div>
          <div class="homepage-mall-section"><div class="shopee-header-section__header shopee-header-section__header--mall"><span class="shopee-header-section__header__title">Shopee Mall</span><span class="right">See All ›</span></div><div class="body"><div class="mall-item"><div class="img"></div>Logitech · Up to 40% off</div><div class="mall-item"><div class="img"></div>Samsung · Vouchers</div><div class="mall-item"><div class="img"></div>Anker · Buy 1 Take 1</div><div class="mall-item"><div class="img"></div>Xiaomi · Free shipping</div></div></div>
          <div class="flash-sale shopee-header-section"><div class="shopee-header-section__header"><span class="shopee-header-section__header__title" style="color:var(--nc-primary)">⚡ Flash Sale</span><span class="shopee-countdown-timer"><span class="shopee-countdown-timer__number">02</span><span class="shopee-countdown-timer__colon">:</span><span class="shopee-countdown-timer__number">14</span><span class="shopee-countdown-timer__colon">:</span><span class="shopee-countdown-timer__number">37</span></span><span class="right">See All ›</span></div><div class="items"><div class="flash-item"><div class="img"><span class="discount">-45%</span></div><div class="price">₱1,299</div><div class="sold"><span>Selling fast</span></div></div><div class="flash-item"><div class="img"><span class="discount">-30%</span></div><div class="price">₱899</div><div class="sold"><span>120 sold</span></div></div><div class="flash-item"><div class="img"><span class="discount">-60%</span></div><div class="price">₱349</div><div class="sold"><span>Selling fast</span></div></div><div class="flash-item"><div class="img"><span class="discount">-20%</span></div><div class="price">₱2,499</div><div class="sold"><span>48 sold</span></div></div><div class="flash-item"><div class="img"><span class="discount">-50%</span></div><div class="price">₱199</div><div class="sold"><span>Selling fast</span></div></div></div></div>
          <div class="shopee-header-section"><div class="shopee-header-section__header"><span class="shopee-header-section__header__title" style="color:var(--nc-primary)">Daily Discover</span></div></div>
          <div class="product-grid"><div class="product-card"><div class="img"><span class="mall">Mall</span></div><div class="body"><div class="name">Mechanical Keyboard 75% Hot-swap RGB Gasket Mount</div><span class="tag">10% off</span><div class="price"><small>₱</small>2,499</div><div class="meta"><span class="stars">★★★★★</span><span>1.2k sold</span></div></div><div class="footer"><span>Quezon City</span><span class="free">Free shipping</span></div></div><div class="product-card"><div class="img"><span class="badge">Preferred</span><span class="JH7cJR">Local</span></div><div class="body"><div class="name">USB-C Dock 11-in-1 4K HDMI PD 100W</div><span class="tag">COD</span><div class="price"><small>₱</small>1,850</div><div class="meta"><span class="stars">★★★★☆</span><span>860 sold</span></div></div><div class="footer"><span>Makati</span></div></div><div class="product-card"><div class="img"></div><div class="body"><div class="name">Ergonomic Wireless Mouse Silent Click</div><div class="price"><small>₱</small>599</div><div class="meta"><span class="stars">★★★★★</span><span>3.4k sold</span></div></div><div class="footer"><span>Pasig</span><span class="free">Free shipping</span></div></div><div class="product-card"><div class="img"><span class="mall">Mall</span></div><div class="body"><div class="name">27" IPS Monitor 100Hz 1080p</div><span class="tag">Voucher</span><div class="price"><small>₱</small>7,990</div><div class="meta"><span class="stars">★★★★★</span><span>210 sold</span></div></div><div class="footer"><span>Metro Manila</span></div></div><div class="product-card"><div class="img"></div><div class="body"><div class="name">Laptop Stand Aluminium Adjustable</div><div class="price"><small>₱</small>450</div><div class="meta"><span class="stars">★★★★☆</span><span>5.1k sold</span></div></div><div class="footer"><span>Cebu</span><span class="free">Free shipping</span></div></div></div>
          <div class="shopee-page-controller"><button><i>‹</i></button><button class="shopee-button-solid--primary">1</button><button>2</button><button>3</button><button><i>…</i></button><button><i>›</i></button></div>
        </div>
        <footer><div class="cols"><div><h4>Customer Service</h4><a href="#">Help Centre</a><a href="#">How To Buy</a><a href="#">Return &amp; Refund</a></div><div><h4>About Shopee</h4><a href="#">About Us</a><a href="#">Careers</a><a href="#">Policies</a></div><div><h4>Payment</h4><div class="payments"><span></span><span></span><span></span><span></span></div></div><div><h4>Follow Us</h4><a href="#">Facebook</a><a href="#">Instagram</a></div><div><h4>Shopee App Download</h4><div class="payments"><span style="width:80px;height:80px"></span></div></div></div><div class="legal">© 2026 Shopee. All Rights Reserved.</div></footer></div>
    </Pair>
  </Section>

  <Section id="controls" title="Stardust controls" lead="[class^=stardust-button] variants, input, checkbox, radio, switch, tabs, labels, text roles" min="420px">
    <Pair name="stardust-button variants">
      <button class="stardust-button stardust-button--ghost" aria-label="Close"><svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="1.5"/></svg></button>
      <button class="stardust-button">Default</button><button class="stardust-button stardust-button--primary">Buy Now</button><button class="stardust-button stardust-button--secondary">Add To Cart</button><button class="stardust-button stardust-button--ghost">Ghost</button><button class="stardust-button stardust-button--disabled">Sold Out</button><button class="stardust-button stardust-button--primary stardust-button--large">Check Out</button>
    </Pair>
    <Pair name="stardust-input + checkbox/radio/switch + tabs">
      <input class="stardust-input" value="Search in shop" /> <div><input class="stardust-input stardust-input--error" value="" /><div class="stardust-form-error">Please enter a valid phone number</div></div>
      <span><span class="stardust-checkbox stardust-checkbox--checked">✓</span> <span class="stardust-checkbox"></span> <span class="stardust-radio stardust-radio--checked"></span> <span class="stardust-radio"></span> <span class="stardust-switch stardust-switch--on"></span> <span class="stardust-switch"></span></span>
      <div class="stardust-tabs" style="width:100%"><button class="stardust-tabs-header__tab stardust-tabs-header__tab--active">All</button><button class="stardust-tabs-header__tab">To Pay</button><button class="stardust-tabs-header__tab">To Ship</button><button class="stardust-tabs-header__tab">Completed</button></div>
    </Pair>
    <Pair name="labels / text roles / avatar / placeholder">
      <span><span class="shopee-label">-45%</span> <span class="shopee-label shopee-label--outline">Voucher</span> <span class="shopee-label shopee-label--mall">Mall</span> <span class="shopee-label shopee-label--preferred">Preferred</span> <span class="shopee-label shopee-label--cod">COD</span></span>
      <p style="margin:0">Primary · <span class="text-secondary">Secondary</span> · <span class="text-tertiary">Tertiary</span> · <span class="disabled-text">Disabled</span> · <a class="text-link" href="#">Text link</a> · <span class="blue">Blue</span> · <span class="green">Green</span> · <span class="rating">★★★★★ 4.9</span></p>
      <span><span class="shopee-avatar"></span></span> <div class="placeholder" style="width:100%"></div>
    </Pair>
  </Section>

  <Section id="overlays" title="Overlays and feedback" lead="Dropdown, popover, modal, toast on the mask, alerts (caution/error/success/primary), voucher" min="420px">
    <Pair name=".stardust-dropdown + .stardust-popover + .shopee-modal">
      <div role="menu" class="stardust-dropdown"><div class="stardust-dropdown__item">My Account</div><div class="stardust-dropdown__item">My Purchase</div><div class="stardust-dropdown__item">Logout</div></div>
      <div role="tooltip" class="stardust-popover"><b>Shopee Coins</b><p style="margin:4px 0 0" class="text-secondary">You have 1,240 coins. Redeem at checkout.</p></div>
      <div role="dialog" class="shopee-modal"><h2>Remove item?</h2><p>Remove "Mechanical Keyboard 75%" from your cart?</p><div class="foot"><button class="stardust-button">Cancel</button><button class="stardust-button stardust-button--primary">Yes, remove</button></div></div>
    </Pair>
    <Pair name=".shopee-toast + .shopee-alert variants + .voucher">
      <div class="shopee-toast">✓ Item has been added to your shopping cart</div>
      <div class="shopee-alert shopee-alert--caution">⚠ Your order will be cancelled if not paid in 24 hours.</div><div class="shopee-alert shopee-alert--error">✕ Payment failed. Please try again.</div><div class="shopee-alert shopee-alert--success">✓ Order placed.</div><div class="shopee-alert shopee-alert--primary">🎁 Free shipping voucher applied.</div>
      <div class="voucher"><div class="left">FREE<br/>SHIPPING</div><div class="right"><b>₱0 shipping fee</b><small>Min. spend ₱0 · Valid until 30.09.2026</small><button class="stardust-button stardust-button--secondary">Claim</button></div></div>
    </Pair>
  </Section>
</SitePage>
