; Lime Glass - Spicetify color scheme
; Default + base palette mappings for Spotify desktop client.

[base]
text                = F8F8F8
subtext             = 6B7280
sidebar-text        = F8F8F8
main                = 07080A
sidebar             = 0A0A0D
player              = 0D0D10
card                = 121216
shadow              = 000000
selected-row        = 121216
button              = A8E635
button-active       = C1FF58
button-disabled     = 4B5563
tab-active          = 121216
notification        = A8E635
notification-error  = ED254E
misc                = 8BC406
equalizer           = 71F79F

[dark]
text                = F8F8F8
subtext             = 6B7280
sidebar-text        = F8F8F8
main                = 07080A
sidebar             = 0A0A0D
player              = 0D0D10
card                = 121216
shadow              = 000000
selected-row        = 121216
button              = A8E635
button-active       = C1FF58
button-disabled     = 4B5563
tab-active          = 121216
notification        = A8E635
notification-error  = ED254E
misc                = 8BC406
equalizer           = 71F79F
