; Lime Glass - Spicetify color scheme
; Default + base palette mappings for Spotify desktop client.

[base]
text                = F8F8F8
subtext             = 6B7280
sidebar-text        = F8F8F8
main                = 07080A
sidebar             = 0A0A0D
player              = 0D0D10
card                = 121216
shadow              = 000000
selected-row        = 121216
button              = A6C9A6
button-active       = C0E3C0
button-disabled     = 4B5563
tab-active          = 121216
notification        = A6C9A6
notification-error  = ED254E
misc                = 89A889
equalizer           = 3FFABB

[dark]
text                = F8F8F8
subtext             = 6B7280
sidebar-text        = F8F8F8
main                = 07080A
sidebar             = 0A0A0D
player              = 0D0D10
card                = 121216
shadow              = 000000
selected-row        = 121216
button              = A6C9A6
button-active       = C0E3C0
button-disabled     = 4B5563
tab-active          = 121216
notification        = A6C9A6
notification-error  = ED254E
misc                = 89A889
equalizer           = 3FFABB
