/* The token file's derived palette, read from tokens/out/json-tokens.json —
 * generated by codegen.py, never copied. The desktop pages compare every
 * surface's rendered roles against these hexes, so a layer that drifted off
 * the TOML shows up as a red cell on /desktop/, not on the live desktop. */
import json from '../../../../tokens/out/json-tokens.json';

type Swatch = { hex: string; oklch: string };
const derived = (json as unknown as { _derived: { default_variant: string; palettes: Record<string, Record<string, Swatch>> } })._derived;

export const VARIANT = derived.default_variant;
export const PALETTE: Record<string, string> = Object.fromEntries(
  Object.entries(derived.palettes[VARIANT]).map(([k, v]) => [k, v.hex.toUpperCase()])
);
export const TOKENS = json as unknown as Record<string, any>;

/* Hex (#RGB, #RRGGBB, #RRGGBBAA) to 0-255 channels plus alpha 0-1. */
export function rgba(hex: string): [number, number, number, number] {
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const n = (i: number) => parseInt(h.slice(i, i + 2), 16);
  return [n(0), n(2), n(4), h.length === 8 ? n(6) / 255 : 1];
}

const lin = (c: number) => {
  const s = c / 255;
  return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
};
export const luminance = (hex: string) => {
  const [r, g, b] = rgba(hex);
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
};
/* WCAG 2 contrast ratio of two opaque colours. */
export function contrast(a: string, b: string): number {
  const [x, y] = [luminance(a), luminance(b)].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
}

/* Normalise any colour string a page produces to upper-case #RRGGBB[AA]. */
export function normHex(v: string): string {
  const s = v.trim();
  if (/^#[0-9a-f]{3}$/i.test(s)) return `#${s.slice(1).split('').map((c) => c + c).join('')}`.toUpperCase();
  const m = s.match(/^rgba?\((\d+)[,\s]+(\d+)[,\s]+(\d+)(?:[,\s/]+([\d.]+%?))?\)$/i);
  if (m) {
    const hex = [m[1], m[2], m[3]].map((x) => Number(x).toString(16).padStart(2, '0')).join('');
    const a = m[4] === undefined ? 1 : m[4].endsWith('%') ? Number(m[4].slice(0, -1)) / 100 : Number(m[4]);
    return `#${hex}${a < 1 ? Math.round(a * 255).toString(16).padStart(2, '0') : ''}`.toUpperCase();
  }
  return s.toUpperCase();
}
