#!/usr/bin/env python3
"""
Indigo Glass - token codegen.

Reads tokens/indigo-glass.tokens.toml and emits derived per-layer
artifacts:

    tokens/out/css-vars.css        # CSS custom properties (web/Stylus)
    tokens/out/scss-vars.scss      # Sass equivalent
    tokens/out/json-tokens.json    # JSON (VSCode/web/JS consumers)
    tokens/out/kde-palette.colors  # KDE color scheme partial
    tokens/out/wt-scheme.json      # Windows Terminal scheme partial
    tokens/out/density.css         # Compact-density CSS rules

Usage:
    python3 tokens/codegen.py             # emit all
    python3 tokens/codegen.py --check     # exit 1 if any out-of-date

Requires Python 3.11+ (uses tomllib).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ImportError:
    print("ERROR: Python 3.11+ required (need tomllib).", file=sys.stderr)
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
TOKENS_FILE = REPO_ROOT / "tokens" / "indigo-glass.tokens.toml"
OUT_DIR = REPO_ROOT / "tokens" / "out"


def load_tokens() -> dict:
    with TOKENS_FILE.open("rb") as f:
        return tomllib.load(f)


def emit_css_vars(t: dict) -> str:
    lines = [
        "/* Indigo Glass design tokens - CSS custom properties */",
        "/* Generated by tokens/codegen.py from tokens/indigo-glass.tokens.toml */",
        "/* DO NOT EDIT - regenerate via `python3 tokens/codegen.py` */",
        "",
        ":root {",
        "  /* Palette - sRGB */",
    ]
    for k, v in t["palette"]["sRGB"].items():
        lines.append(f"  --ig-{k.replace('_', '-')}: {v};")

    lines.extend(["", "  /* Spacing */"])
    for k, v in t["spacing"].items():
        lines.append(f"  --ig-{k.replace('_', '-')}: {v}px;")

    lines.extend(["", "  /* Radius */"])
    for k, v in t["radius"].items():
        suffix = "px" if k != "full" else "px"
        lines.append(f"  --ig-radius-{k}: {v}{suffix};")

    lines.extend(["", "  /* Blur */"])
    for k, v in t["blur"].items():
        lines.append(f"  --ig-blur-{k}: {v}px;")

    lines.extend(["", "  /* Opacity */"])
    for k, v in t["opacity"].items():
        lines.append(f"  --ig-opacity-{k.replace('_', '-')}: {v};")

    lines.extend(["", "  /* Shadow */"])
    for k, v in t["shadow"].items():
        lines.append(f"  --ig-shadow-{k.replace('_', '-')}: {v};")

    lines.extend(["", "  /* Type scale (pt) */"])
    for k, v in t["type"]["scale"].items():
        if isinstance(v, (int, float)) and k.endswith("_pt"):
            lines.append(f"  --ig-type-{k.replace('_pt', '').replace('_', '-')}-pt: {v}pt;")

    lines.extend(["", "  /* Type roles (pt) */"])
    for k, v in t["type"]["roles"].items():
        lines.append(f"  --ig-{k.replace('_pt', '').replace('_', '-')}-pt: {v}pt;")

    lines.extend(["", "  /* Line height */"])
    for k, v in t["type"]["line_height"].items():
        lines.append(f"  --ig-lh-{k}: {v};")

    lines.extend(["", "  /* Motion */"])
    for k, v in t["motion"]["duration_ms"].items():
        lines.append(f"  --ig-dur-{k}: {v}ms;")
    for k, v in t["motion"]["easing"].items():
        lines.append(f"  --ig-ease-{k}: {v};")

    lines.append("}")
    lines.append("")

    # P3 wide-gamut override
    lines.extend([
        "/* Display-P3 wide-gamut overlay */",
        "@media (color-gamut: p3) {",
        "  :root {",
    ])
    for k, v in t["palette"]["P3"].items():
        lines.append(f"    --ig-{k.replace('_', '-')}: {v};")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Reduced transparency a11y branch
    lines.extend([
        "/* Reduced transparency - disable backdrop blur + raise opacity */",
        "@media (prefers-reduced-transparency: reduce) {",
        "  :root {",
        f"    --ig-blur-md: 0;",
        f"    --ig-blur-lg: 0;",
        f"    --ig-blur-xl: 0;",
        f"    --ig-opacity-glass-panel: 1.0;",
        f"    --ig-opacity-glass-panel-lo: 1.0;",
        f"    --ig-opacity-glass-panel-hi: 1.0;",
        "  }",
        "}",
        "",
        "/* Reduced motion - kill durations */",
        "@media (prefers-reduced-motion: reduce) {",
        "  :root {",
        "    --ig-dur-quick: 0ms;",
        "    --ig-dur-default: 0ms;",
        "    --ig-dur-slow: 0ms;",
        "    --ig-dur-hero: 0ms;",
        "  }",
        "}",
        "",
    ])

    return "\n".join(lines)


def emit_scss_vars(t: dict) -> str:
    css = emit_css_vars(t)
    # Quick conversion: --ig-foo: VAL; -> $ig-foo: VAL;
    out = []
    out.append("// Indigo Glass design tokens - Sass variables")
    out.append("// Generated by tokens/codegen.py")
    out.append("")
    for line in css.split("\n"):
        s = line.strip()
        if s.startswith("--ig-") and ":" in s:
            k, v = s.split(":", 1)
            k = k.replace("--", "$").strip()
            v = v.rstrip(";").strip()
            out.append(f"{k}: {v};")
    return "\n".join(out) + "\n"


def emit_json(t: dict) -> str:
    return json.dumps(t, indent=2) + "\n"


def emit_kde_colors(t: dict) -> str:
    """KDE color scheme partial. Merge into IndigoGlass.colors."""
    p = t["palette"]["sRGB"]

    def hex_to_rgb(h: str) -> str:
        h = h.lstrip("#")
        if len(h) >= 6:
            r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
            return f"{r},{g},{b}"
        return "0,0,0"

    lines = [
        "# Indigo Glass - KDE color scheme partial",
        "# Generated by tokens/codegen.py - merge into IndigoGlass.colors",
        "",
        "[General]",
        "Name=IndigoGlass",
        "shadeSortColumn=true",
        "",
        "[Colors:Window]",
        f"BackgroundNormal={hex_to_rgb(p['surface'])}",
        f"BackgroundAlternate={hex_to_rgb(p['surface_alt'])}",
        f"ForegroundNormal={hex_to_rgb(p['text'])}",
        f"ForegroundInactive={hex_to_rgb(p['text_muted'])}",
        f"ForegroundActive={hex_to_rgb(p['indigo_hi'])}",
        f"ForegroundLink={hex_to_rgb(p['indigo_hi'])}",
        f"ForegroundVisited={hex_to_rgb(p['violet'])}",
        f"ForegroundNegative={hex_to_rgb(p['negative'])}",
        f"ForegroundPositive={hex_to_rgb(p['positive'])}",
        f"ForegroundNeutral={hex_to_rgb(p['amber'])}",
        f"DecorationFocus={hex_to_rgb(p['indigo'])}",
        f"DecorationHover={hex_to_rgb(p['indigo_hi'])}",
        "",
        "[Colors:Selection]",
        f"BackgroundNormal={hex_to_rgb(p['indigo'])}",
        f"BackgroundAlternate={hex_to_rgb(p['indigo_hi'])}",
        "ForegroundNormal=255,255,255",
        f"ForegroundActive={hex_to_rgb(p['text'])}",
        "",
        "[Colors:View]",
        f"BackgroundNormal={hex_to_rgb(p['base'])}",
        f"BackgroundAlternate={hex_to_rgb(p['surface'])}",
        f"ForegroundNormal={hex_to_rgb(p['text'])}",
        f"ForegroundInactive={hex_to_rgb(p['text_muted'])}",
        f"ForegroundActive={hex_to_rgb(p['indigo_hi'])}",
        f"DecorationFocus={hex_to_rgb(p['indigo'])}",
        f"DecorationHover={hex_to_rgb(p['indigo_hi'])}",
        "",
        "[Colors:Button]",
        f"BackgroundNormal={hex_to_rgb(p['surface_alt'])}",
        f"BackgroundAlternate={hex_to_rgb(p['surface'])}",
        f"ForegroundNormal={hex_to_rgb(p['text'])}",
        f"DecorationFocus={hex_to_rgb(p['indigo_hi'])}",
        f"DecorationHover={hex_to_rgb(p['indigo_hi'])}",
        "",
        "[Colors:Tooltip]",
        f"BackgroundNormal={hex_to_rgb(p['surface_alt'])}",
        f"ForegroundNormal={hex_to_rgb(p['text'])}",
        "",
        "[WM]",
        f"activeBackground={hex_to_rgb(p['surface'])}",
        f"activeForeground={hex_to_rgb(p['text'])}",
        f"inactiveBackground={hex_to_rgb(p['sidebar'])}",
        f"inactiveForeground={hex_to_rgb(p['text_muted'])}",
        f"activeBlend={hex_to_rgb(p['indigo'])}",
        f"inactiveBlend={hex_to_rgb(p['text_dim'])}",
        "",
    ]
    return "\n".join(lines)


def emit_wt_scheme(t: dict) -> str:
    """Windows Terminal scheme."""
    p = t["palette"]["sRGB"]
    scheme = {
        "name": "Indigo Glass",
        "background": p["base"],
        "foreground": p["text"],
        "cursorColor": p["indigo_hi"],
        "selectionBackground": p["indigo"],
        "black":         p["sidebar"],
        "red":           p["negative"],
        "green":         p["positive"],
        "yellow":        p["amber"],
        "blue":          p["indigo"],
        "purple":        p["violet"],
        "cyan":          "#67E8F9",
        "white":         p["text"],
        "brightBlack":   p["text_muted"],
        "brightRed":     "#FF5272",
        "brightGreen":   "#8CFFB4",
        "brightYellow":  "#FFD250",
        "brightBlue":    p["indigo_hi"],
        "brightPurple":  "#C8B5FF",
        "brightCyan":    "#A5F3FC",
        "brightWhite":   "#FFFFFF",
    }
    return json.dumps(scheme, indent=2) + "\n"


def emit_density_css(t: dict) -> str:
    s = t["spacing"]
    r = t["radius"]
    lines = [
        "/* Indigo Glass - compact density rules */",
        "/* Generated by tokens/codegen.py - see docs/DENSITY.md */",
        "",
        ":root {",
        f"  --ig-density-button-pad-y: {s['button_pad_y']}px;",
        f"  --ig-density-button-pad-x: {s['button_pad_x']}px;",
        f"  --ig-density-input-pad-y: {s['input_pad_y']}px;",
        f"  --ig-density-input-pad-x: {s['input_pad_x']}px;",
        f"  --ig-density-list-row-pad-y: {s['list_row_pad_y']}px;",
        f"  --ig-density-list-row-pad-x: {s['list_row_pad_x']}px;",
        f"  --ig-density-list-row-gap: {s['list_row_gap']}px;",
        "}",
        "",
        "/* Generic compact rules (override site defaults) */",
        "html body button:not([class*=\"icon\"]):not([class*=\"Icon\"]) {",
        "  padding: var(--ig-density-button-pad-y) var(--ig-density-button-pad-x) !important;",
        "}",
        "",
        "html body input[type=\"text\"],",
        "html body input[type=\"search\"],",
        "html body input[type=\"email\"],",
        "html body input[type=\"url\"],",
        "html body input[type=\"password\"],",
        "html body input[type=\"number\"],",
        "html body select,",
        "html body textarea {",
        "  padding: var(--ig-density-input-pad-y) var(--ig-density-input-pad-x) !important;",
        "}",
        "",
    ]
    return "\n".join(lines)


WRITERS = [
    ("css-vars.css", emit_css_vars),
    ("scss-vars.scss", emit_scss_vars),
    ("json-tokens.json", emit_json),
    ("kde-palette.colors", emit_kde_colors),
    ("wt-scheme.json", emit_wt_scheme),
    ("density.css", emit_density_css),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any output is out of date")
    args = ap.parse_args()

    t = load_tokens()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    rc = 0
    for fname, fn in WRITERS:
        new = fn(t)
        target = OUT_DIR / fname
        if args.check:
            if not target.exists() or target.read_text() != new:
                print(f"OUT-OF-DATE: {target}")
                rc = 1
            continue
        target.write_text(new)
        print(f"wrote {target}")

    sys.exit(rc)


if __name__ == "__main__":
    main()
