"""Sage Ink -> VSCode role map.

STRUCTURE lives here; VALUES live in tokens/indigo-glass.tokens.toml. Every
entry is a role EXPRESSION resolved per-variant by codegen.emit_vscode_theme,
so the dark and light themes are two renderings of this one map rather than
two files kept in sync by hand.

Expression grammar:
    accent              a palette role from derive_palette()
    accent@50           that role with an 8-digit alpha suffix
    ansi:bright_blue    a slot from [variants.<v>.ansi]
    lift1|lift2|lift3   neutral ladder stepping away from `surface`
    tint:negative@0.12  a role composited over `base` at that alpha, opaque
    marker              maximum contrast against `base` (focus rings)
    on_accent           text/icon legible on an `accent` fill
    outline_hard        the hard silhouette border the ink material projects
    orange              derived: amber's lightness at a red-shifted hue
    transparent         #00000000

Generated once from the hand-typed dark theme (2026-09-22) and maintained
here since. Do not reintroduce raw hex.
"""

VSCODE_COLORS = {'focusBorder': 'marker',
 'foreground': 'text',
 'disabledForeground': 'text_muted',
 'descriptionForeground': 'text_muted',
 'errorForeground': 'negative',
 'icon.foreground': 'accent_hi',
 'selection.background': 'accent@44',
 'widget.shadow': 'accent_alt',
 'widget.border': 'outline_hard',
 'sash.hoverBorder': 'accent_hi',
 'editor.background': 'base',
 'editor.foreground': 'text',
 'editor.lineHighlightBackground': 'text@08',
 'editor.lineHighlightBorder': 'transparent',
 'editor.selectionBackground': 'accent@50',
 'editor.selectionHighlightBackground': 'accent@20',
 'editor.wordHighlightBackground': 'accent@20',
 'editor.wordHighlightStrongBackground': 'accent_alt@30',
 'editor.findMatchBackground': 'amber@50',
 'editor.findMatchHighlightBackground': 'amber@25',
 'editor.findRangeHighlightBackground': 'text@08',
 'editor.hoverHighlightBackground': 'accent@20',
 'editor.rangeHighlightBackground': 'text@06',
 'editor.inactiveSelectionBackground': 'accent@28',
 'editorWhitespace.foreground': 'text@12',
 'editorIndentGuide.background1': 'text@0A',
 'editorIndentGuide.activeBackground1': 'accent_hi@60',
 'editorLineNumber.foreground': 'text_muted',
 'editorLineNumber.activeForeground': 'text',
 'editorCursor.foreground': 'accent_hi',
 'editorCursor.background': 'base',
 'editor.foldBackground': 'text@06',
 'editorBracketMatch.background': 'accent@30',
 'editorBracketMatch.border': 'accent_hi@80',
 'editorBracketHighlight.foreground1': 'accent_hi',
 'editorBracketHighlight.foreground2': 'accent_alt',
 'editorBracketHighlight.foreground3': 'positive',
 'editorBracketHighlight.foreground4': 'amber',
 'editorBracketHighlight.foreground5': 'accent',
 'editorBracketHighlight.foreground6': 'negative',
 'editorBracketHighlight.unexpectedBracket.foreground': 'negative',
 'editorError.foreground': 'negative',
 'editorWarning.foreground': 'amber',
 'editorInfo.foreground': 'accent_hi',
 'editorHint.foreground': 'accent_alt',
 'editorGutter.modifiedBackground': 'accent_hi',
 'editorGutter.addedBackground': 'positive',
 'editorGutter.deletedBackground': 'negative',
 'editorGutter.foldingControlForeground': 'text_muted',
 'diffEditor.insertedTextBackground': 'positive@18',
 'diffEditor.removedTextBackground': 'negative@18',
 'diffEditor.insertedLineBackground': 'positive@10',
 'diffEditor.removedLineBackground': 'negative@10',
 'diffEditor.diagonalFill': 'text@0A',
 'editorOverviewRuler.border': 'transparent',
 'editorOverviewRuler.findMatchForeground': 'amber',
 'editorOverviewRuler.errorForeground': 'negative',
 'editorOverviewRuler.warningForeground': 'amber',
 'editorOverviewRuler.infoForeground': 'accent_hi',
 'editorOverviewRuler.modifiedForeground': 'accent_hi',
 'editorOverviewRuler.addedForeground': 'positive',
 'editorOverviewRuler.deletedForeground': 'negative',
 'editorGroup.border': 'border',
 'editorGroup.dropBackground': 'accent@20',
 'editorGroupHeader.tabsBackground': 'base',
 'editorGroupHeader.tabsBorder': 'border',
 'editorGroupHeader.border': 'transparent',
 'editorPane.background': 'base',
 'tab.activeBackground': 'base',
 'tab.activeForeground': 'text',
 'tab.activeBorder': 'transparent',
 'tab.activeBorderTop': 'marker',
 'tab.inactiveBackground': 'base',
 'tab.inactiveForeground': 'text_muted',
 'tab.border': 'border',
 'tab.hoverBackground': 'sidebar',
 'tab.hoverForeground': 'text',
 'tab.unfocusedActiveBorderTop': 'lift3',
 'tab.unfocusedActiveForeground': 'text_muted',
 'tab.unfocusedInactiveForeground': 'text_muted',
 'tab.lastPinnedBorder': 'border',
 'activityBar.background': 'surface',
 'activityBar.foreground': 'text',
 'activityBar.inactiveForeground': 'text_muted',
 'activityBar.border': 'border',
 'activityBar.activeBorder': 'marker',
 'activityBar.activeBackground': 'transparent',
 'activityBarBadge.background': 'accent',
 'activityBarBadge.foreground': 'on_accent',
 'sideBar.background': 'surface',
 'sideBar.foreground': 'text',
 'sideBar.border': 'border',
 'sideBarTitle.foreground': 'text_muted',
 'sideBarSectionHeader.background': 'surface',
 'sideBarSectionHeader.foreground': 'text_muted',
 'sideBarSectionHeader.border': 'border',
 'list.activeSelectionBackground': 'transparent',
 'list.activeSelectionForeground': 'text',
 'list.inactiveSelectionBackground': 'transparent',
 'list.inactiveSelectionForeground': 'text',
 'list.hoverBackground': 'text@08',
 'list.hoverForeground': 'text',
 'list.focusBackground': 'transparent',
 'list.focusForeground': 'text',
 'list.focusOutline': 'marker',
 'list.focusAndSelectionOutline': 'marker',
 'list.inactiveFocusOutline': 'marker',
 'list.highlightForeground': 'accent_hi',
 'list.focusHighlightForeground': 'accent_alt',
 'list.dropBackground': 'accent@20',
 'list.errorForeground': 'negative',
 'list.warningForeground': 'amber',
 'listFilterWidget.background': 'surface_alt',
 'listFilterWidget.outline': 'accent',
 'listFilterWidget.noMatchesOutline': 'negative',
 'tree.indentGuidesStroke': 'text@10',
 'tree.inactiveIndentGuidesStroke': 'text@06',
 'statusBar.background': 'base',
 'statusBar.foreground': 'text',
 'statusBar.border': 'border',
 'statusBar.debuggingBackground': 'accent_alt',
 'statusBar.debuggingForeground': 'base',
 'statusBar.noFolderBackground': 'base',
 'statusBar.noFolderForeground': 'text_muted',
 'statusBarItem.activeBackground': 'tint:accent@0.16',
 'statusBarItem.hoverBackground': 'text@10',
 'statusBarItem.prominentBackground': 'accent',
 'statusBarItem.prominentForeground': 'on_accent',
 'statusBarItem.prominentHoverBackground': 'accent_hi',
 'statusBarItem.remoteBackground': 'accent',
 'statusBarItem.remoteForeground': 'on_accent',
 'statusBarItem.errorBackground': 'negative',
 'statusBarItem.errorForeground': 'on_accent',
 'statusBarItem.warningBackground': 'amber',
 'statusBarItem.warningForeground': 'base',
 'titleBar.activeBackground': 'surface',
 'titleBar.activeForeground': 'text',
 'titleBar.inactiveBackground': 'surface',
 'titleBar.inactiveForeground': 'text_muted',
 'titleBar.border': 'border',
 'menu.background': 'surface_alt',
 'menu.foreground': 'text',
 'menu.selectionBackground': 'transparent',
 'menu.selectionBorder': 'marker',
 'menu.selectionForeground': 'text',
 'menu.separatorBackground': 'border',
 'menu.border': 'outline_hard',
 # Hovers and suggest widgets: unset, VS Code paints #252526 and a 20%
 # foreground edge (editorColors.ts editorWidget*, editorHoverWidget*).
 'editorWidget.background': 'surface_alt',
 'editorWidget.foreground': 'text',
 'editorWidget.border': 'outline_hard',
 'editorHoverWidget.background': 'surface_alt',
 'editorHoverWidget.foreground': 'text',
 'editorHoverWidget.border': 'outline_hard',
 'menubar.selectionBackground': 'transparent',
 'menubar.selectionBorder': 'marker',
 'menubar.selectionForeground': 'text',
 'button.background': 'accent',
 'button.foreground': 'on_accent',
 'button.hoverBackground': 'accent_hi',
 'button.secondaryBackground': 'surface_alt',
 'button.secondaryForeground': 'text',
 'button.secondaryHoverBackground': 'lift3',
 'button.border': 'outline_hard',
 'button.secondaryBorder': 'outline_hard',
 'checkbox.background': 'surface_alt',
 'checkbox.foreground': 'text',
 'checkbox.border': 'outline_hard',
 'checkbox.selectBackground': 'accent',
 'checkbox.selectBorder': 'accent',
 'input.background': 'surface_alt',
 'input.foreground': 'text',
 'input.border': 'outline_hard',
 'input.placeholderForeground': 'text_muted',
 'inputOption.activeBackground': 'transparent',
 'inputOption.activeBorder': 'marker',
 'inputOption.activeForeground': 'text',
 'inputValidation.errorBackground': 'tint:negative@0.12',
 'inputValidation.errorBorder': 'negative',
 'inputValidation.errorForeground': 'text',
 'inputValidation.warningBackground': 'tint:amber@0.12',
 'inputValidation.warningBorder': 'amber',
 'inputValidation.warningForeground': 'text',
 'inputValidation.infoBackground': 'tint:accent@0.10',
 'inputValidation.infoBorder': 'accent',
 'inputValidation.infoForeground': 'text',
 'dropdown.background': 'surface_alt',
 'dropdown.foreground': 'text',
 'dropdown.border': 'outline_hard',
 'dropdown.listBackground': 'surface_alt',
 'badge.background': 'accent',
 'badge.foreground': 'on_accent',
 'progressBar.background': 'accent',
 'scrollbar.shadow': 'transparent',
 # Tier D (docs/STATE_GRAMMAR.md): a scrollbar thumb is an opaque accent
 # step, not a neutral lift (lift2 measured 1.25:1 on base).
 'scrollbarSlider.background': 'accent_alt',
 'scrollbarSlider.hoverBackground': 'accent',
 'scrollbarSlider.activeBackground': 'accent_hi',
 'terminal.background': 'surface',
 'terminal.foreground': 'text',
 'terminal.selectionBackground': 'accent@40',
 'terminal.findMatchBackground': 'amber@50',
 'terminal.findMatchHighlightBackground': 'amber@25',
 'terminalCursor.background': 'base',
 'terminalCursor.foreground': 'accent_hi',
 'terminal.border': 'border',
 'terminal.tab.activeBorder': 'marker',
 'terminal.ansiBlack': 'ansi:black',
 'terminal.ansiRed': 'ansi:red',
 'terminal.ansiGreen': 'ansi:green',
 'terminal.ansiYellow': 'ansi:yellow',
 'terminal.ansiBlue': 'ansi:blue',
 'terminal.ansiMagenta': 'ansi:magenta',
 'terminal.ansiCyan': 'ansi:cyan',
 'terminal.ansiWhite': 'ansi:white',
 'terminal.ansiBrightBlack': 'ansi:bright_black',
 'terminal.ansiBrightRed': 'ansi:bright_red',
 'terminal.ansiBrightGreen': 'ansi:bright_green',
 'terminal.ansiBrightYellow': 'ansi:bright_yellow',
 'terminal.ansiBrightBlue': 'ansi:bright_blue',
 'terminal.ansiBrightMagenta': 'ansi:bright_magenta',
 'terminal.ansiBrightCyan': 'ansi:bright_cyan',
 'terminal.ansiBrightWhite': 'ansi:bright_white',
 'panel.background': 'surface',
 'panel.border': 'border',
 'panelTitle.activeBorder': 'marker',
 'panelTitle.activeForeground': 'text',
 'panelTitle.inactiveForeground': 'text_muted',
 'panelInput.border': 'outline_hard',
 'peekView.border': 'accent',
 'peekViewEditor.background': 'base',
 'peekViewEditor.matchHighlightBackground': 'amber@40',
 'peekViewEditorGutter.background': 'base',
 'peekViewResult.background': 'surface_alt',
 'peekViewResult.fileForeground': 'text',
 'peekViewResult.lineForeground': 'text_muted',
 'peekViewResult.matchHighlightBackground': 'amber@30',
 'peekViewResult.selectionBackground': 'text@14',
 'peekViewResult.selectionForeground': 'text',
 'peekViewTitle.background': 'surface_alt',
 'peekViewTitleLabel.foreground': 'text',
 'peekViewTitleDescription.foreground': 'text_muted',
 'notifications.background': 'surface_alt',
 'notifications.foreground': 'text',
 'notifications.border': 'outline_hard',
 'notificationCenter.border': 'outline_hard',
 'notificationCenterHeader.background': 'surface_alt',
 'notificationCenterHeader.foreground': 'text',
 'notificationToast.border': 'outline_hard',
 'notificationLink.foreground': 'accent_hi',
 'notificationsErrorIcon.foreground': 'negative',
 'notificationsWarningIcon.foreground': 'amber',
 'notificationsInfoIcon.foreground': 'accent_hi',
 'extensionButton.prominentBackground': 'accent',
 'extensionButton.prominentForeground': 'on_accent',
 'extensionButton.prominentHoverBackground': 'accent_hi',
 'extensionBadge.remoteBackground': 'accent',
 'extensionBadge.remoteForeground': 'on_accent',
 'extensionIcon.starForeground': 'amber',
 'extensionIcon.verifiedForeground': 'positive',
 'extensionIcon.preReleaseForeground': 'accent_alt',
 'quickInput.background': 'surface_alt',
 'quickInput.foreground': 'text',
 'quickInputTitle.background': 'surface_alt',
 'quickInputList.focusBackground': 'lift2',
 'quickInputList.focusForeground': 'text',
 'pickerGroup.border': 'outline_hard',
 'pickerGroup.foreground': 'accent_hi',
 'breadcrumb.background': 'base',
 'breadcrumb.foreground': 'text_muted',
 'breadcrumb.focusForeground': 'text',
 'breadcrumb.activeSelectionForeground': 'accent_hi',
 'breadcrumbPicker.background': 'surface_alt',
 'gitDecoration.modifiedResourceForeground': 'amber',
 'gitDecoration.deletedResourceForeground': 'negative',
 'gitDecoration.untrackedResourceForeground': 'positive',
 'gitDecoration.ignoredResourceForeground': 'text_muted',
 'gitDecoration.conflictingResourceForeground': 'accent_alt',
 'gitDecoration.submoduleResourceForeground': 'accent_hi',
 'gitDecoration.addedResourceForeground': 'positive',
 'gitDecoration.renamedResourceForeground': 'accent_hi',
 'gitDecoration.stageModifiedResourceForeground': 'accent_hi',
 'gitDecoration.stageDeletedResourceForeground': 'ansi:bright_red',
 'merge.currentHeaderBackground': 'accent@50',
 'merge.currentContentBackground': 'accent@20',
 'merge.incomingHeaderBackground': 'accent_alt@50',
 'merge.incomingContentBackground': 'accent_alt@20',
 'merge.commonHeaderBackground': 'text_muted@50',
 'merge.commonContentBackground': 'text_muted@20',
 'debugToolBar.background': 'surface_alt',
 'debugToolBar.border': 'outline_hard',
 'debugIcon.breakpointForeground': 'negative',
 'debugIcon.breakpointDisabledForeground': 'text_muted',
 'debugIcon.startForeground': 'positive',
 'debugIcon.pauseForeground': 'amber',
 'debugIcon.stopForeground': 'negative',
 'debugIcon.continueForeground': 'positive',
 'debugIcon.stepOverForeground': 'accent_hi',
 'debugIcon.stepIntoForeground': 'accent_hi',
 'debugIcon.stepOutForeground': 'accent_hi',
 'debugIcon.restartForeground': 'positive',
 'debugIcon.disconnectForeground': 'negative',
 'debugConsole.infoForeground': 'accent_hi',
 'debugConsole.warningForeground': 'amber',
 'debugConsole.errorForeground': 'negative',
 'debugConsole.sourceForeground': 'text',
 'debugConsoleInputIcon.foreground': 'accent_hi',
 'settings.headerForeground': 'text',
 'settings.modifiedItemIndicator': 'accent',
 'settings.dropdownBackground': 'surface_alt',
 'settings.dropdownForeground': 'text',
 'settings.dropdownBorder': 'outline_hard',
 'settings.checkboxBackground': 'surface_alt',
 'settings.checkboxForeground': 'text',
 'settings.checkboxBorder': 'outline_hard',
 'settings.textInputBackground': 'surface_alt',
 'settings.textInputForeground': 'text',
 'settings.textInputBorder': 'outline_hard',
 'settings.numberInputBackground': 'surface_alt',
 'settings.numberInputForeground': 'text',
 'settings.numberInputBorder': 'outline_hard',
 'settings.focusedRowBackground': 'lift1',
 'textLink.foreground': 'accent_hi',
 'textLink.activeForeground': 'accent_alt',
 'textBlockQuote.background': 'surface_alt',
 'textBlockQuote.border': 'accent',
 'textCodeBlock.background': 'surface_alt',
 'textPreformat.foreground': 'accent_hi',
 'textSeparator.foreground': 'border',
 'welcomePage.background': 'base',
 'welcomePage.tileBackground': 'surface_alt',
 'welcomePage.tileHoverBackground': 'lift3',
 'walkThrough.embeddedEditorBackground': 'base',
 'editorMarkerNavigation.background': 'surface_alt',
 'editorMarkerNavigationError.background': 'negative',
 'editorMarkerNavigationError.headerBackground': 'tint:negative@0.18',
 'editorMarkerNavigationWarning.background': 'amber',
 'editorMarkerNavigationWarning.headerBackground': 'tint:amber@0.18',
 'editorMarkerNavigationInfo.background': 'accent',
 'editorMarkerNavigationInfo.headerBackground': 'tint:accent@0.14',
 'charts.foreground': 'text',
 'charts.lines': 'border',
 'charts.red': 'ansi:red',
 'charts.blue': 'ansi:blue',
 'charts.yellow': 'ansi:yellow',
 'charts.orange': 'orange',
 'charts.green': 'ansi:green',
 'charts.purple': 'ansi:magenta'}

VSCODE_TOKEN_COLORS = [{'name': 'Comment',
  'scope': ['comment', 'punctuation.definition.comment'],
  'settings': {'fontStyle': 'italic', 'foreground': 'text_muted'}},
 {'name': 'Variable',
  'scope': ['variable', 'variable.other', 'variable.parameter'],
  'settings': {'foreground': 'text'}},
 {'name': 'Variable language (this/self)',
  'scope': ['variable.language', 'variable.language.this'],
  'settings': {'fontStyle': 'italic', 'foreground': 'accent_alt'}},
 {'name': 'Constant',
  'scope': ['constant',
            'constant.language',
            'constant.numeric',
            'constant.character',
            'constant.other'],
  'settings': {'foreground': 'accent_alt'}},
 {'name': 'Boolean / null',
  'scope': ['constant.language.boolean',
            'constant.language.null',
            'constant.language.undefined'],
  'settings': {'foreground': 'accent_alt'}},
 {'name': 'String',
  'scope': ['string', 'string.quoted'],
  'settings': {'foreground': 'positive'}},
 {'name': 'String escape',
  'scope': ['constant.character.escape', 'string.regexp'],
  'settings': {'foreground': 'amber'}},
 {'name': 'Template expression punctuation',
  'scope': ['punctuation.definition.template-expression',
            'punctuation.section.embedded'],
  'settings': {'foreground': 'accent_hi'}},
 {'name': 'Keyword',
  'scope': ['keyword', 'keyword.control', 'keyword.operator.new'],
  'settings': {'foreground': 'accent_hi'}},
 {'name': 'Operator',
  'scope': ['keyword.operator', 'punctuation.separator'],
  'settings': {'foreground': 'ansi:blue'}},
 {'name': 'Storage (var/let/const/function/class)',
  'scope': ['storage', 'storage.type', 'storage.modifier'],
  'settings': {'foreground': 'accent_hi'}},
 {'name': 'Function name',
  'scope': ['entity.name.function',
            'meta.function-call entity.name.function',
            'support.function',
            'meta.definition.method entity.name.function'],
  'settings': {'foreground': 'amber'}},
 {'name': 'Class / Type',
  'scope': ['entity.name.class',
            'entity.name.type',
            'support.class',
            'support.type',
            'entity.other.inherited-class'],
  'settings': {'foreground': 'accent_alt'}},
 {'name': 'Namespace / Module',
  'scope': ['entity.name.namespace', 'entity.name.module', 'support.module'],
  'settings': {'foreground': 'accent_alt'}},
 {'name': 'Decorator',
  'scope': ['meta.decorator',
            'punctuation.decorator',
            'entity.name.function.decorator'],
  'settings': {'fontStyle': 'italic', 'foreground': 'amber'}},
 {'name': 'Property / member',
  'scope': ['variable.other.property',
            'variable.other.object.property',
            'meta.property.object',
            'support.variable.property'],
  'settings': {'foreground': 'text'}},
 {'name': 'Tag',
  'scope': ['entity.name.tag', 'meta.tag', 'punctuation.definition.tag'],
  'settings': {'foreground': 'accent_hi'}},
 {'name': 'Tag attribute',
  'scope': ['entity.other.attribute-name'],
  'settings': {'fontStyle': 'italic', 'foreground': 'accent_alt'}},
 {'name': 'JSON key',
  'scope': ['support.type.property-name.json', 'meta.structure.dictionary.key.json'],
  'settings': {'foreground': 'accent_hi'}},
 {'name': 'CSS property name',
  'scope': ['support.type.property-name.css', 'meta.property-name.css'],
  'settings': {'foreground': 'accent_hi'}},
 {'name': 'CSS value',
  'scope': ['support.constant.property-value.css', 'meta.property-value.css'],
  'settings': {'foreground': 'text'}},
 {'name': 'Markdown heading',
  'scope': ['markup.heading', 'entity.name.section.markdown'],
  'settings': {'fontStyle': 'bold', 'foreground': 'accent_hi'}},
 {'name': 'Markdown bold',
  'scope': ['markup.bold'],
  'settings': {'fontStyle': 'bold', 'foreground': 'text'}},
 {'name': 'Markdown italic',
  'scope': ['markup.italic'],
  'settings': {'fontStyle': 'italic', 'foreground': 'text'}},
 {'name': 'Markdown link',
  'scope': ['markup.underline.link', 'string.other.link'],
  'settings': {'foreground': 'accent_alt'}},
 {'name': 'Markdown inline code',
  'scope': ['markup.inline.raw', 'markup.fenced_code'],
  'settings': {'foreground': 'positive'}},
 {'name': 'Markdown quote',
  'scope': ['markup.quote'],
  'settings': {'fontStyle': 'italic', 'foreground': 'text_muted'}},
 {'name': 'Diff inserted',
  'scope': ['markup.inserted'],
  'settings': {'foreground': 'positive'}},
 {'name': 'Diff deleted',
  'scope': ['markup.deleted'],
  'settings': {'foreground': 'negative'}},
 {'name': 'Diff changed',
  'scope': ['markup.changed'],
  'settings': {'foreground': 'amber'}},
 {'name': 'Invalid',
  'scope': ['invalid', 'invalid.illegal'],
  'settings': {'foreground': 'negative'}},
 {'name': 'Deprecated',
  'scope': ['invalid.deprecated'],
  'settings': {'fontStyle': 'strikethrough', 'foreground': 'orange'}},
 {'name': 'Punctuation',
  'scope': ['punctuation', 'meta.brace', 'meta.bracket', 'meta.parens'],
  'settings': {'foreground': 'text_muted'}},
 {'name': 'Embedded punctuation (JSX/TSX braces)',
  'scope': ['punctuation.section.embedded.begin', 'punctuation.section.embedded.end'],
  'settings': {'foreground': 'accent_hi'}}]

VSCODE_SEMANTIC = {'namespace': 'accent_alt',
 'type': 'accent_alt',
 'class': 'accent_alt',
 'interface': 'accent_alt',
 'enum': 'accent_alt',
 'typeParameter': 'accent_alt',
 'function': 'amber',
 'method': 'amber',
 'macro': 'amber',
 'variable': 'text',
 'parameter': 'text',
 'property': 'text',
 'enumMember': 'accent_alt',
 'event': 'amber',
 'keyword': 'accent_hi',
 'modifier': 'accent_hi',
 'comment': {'foreground': 'text_muted', 'fontStyle': 'italic'},
 'string': 'positive',
 'number': 'accent_alt',
 'regexp': 'amber',
 'operator': 'ansi:blue',
 'decorator': {'foreground': 'amber', 'fontStyle': 'italic'},
 '*.deprecated': {'fontStyle': 'strikethrough'},
 '*.readonly': {'fontStyle': 'italic'}}
